import styles from './Nft.module.css'
function Nft(props) {

    const mouseOver = (h,s) =>{
        let hide = document.querySelector(`.${h}`);
        let seek = document.querySelector(`.${s}`);
        hide.style.opacity = "0";
        hide.style.zIndex = "-1";
        seek.style.zIndex = "999";
        seek.style.opacity = "1";

        console.log(h,s)
    }

    const mouseOut = (h,s) =>{
        let hide = document.querySelector(`.${h}`);
        let seek = document.querySelector(`.${s}`);
        hide.style.opacity = "1";
        hide.style.zIndex = "999";
        seek.style.zIndex = "-1";
        seek.style.opacity = "0";
    }

    const autoGeneratedName = `btn${Math.floor(Math.random() * 999999)}`;
    const autoGeneratedNameTwo = `btn${Math.floor(Math.random() * 999999)}`;

    return (
        <div className={styles.NftWrapper}>
            <img src={`${props.src}`} alt={`${props.name}`} />
            <p>{props.name}</p>

            <p className={styles.hide + " " + autoGeneratedName} onMouseOver={() => mouseOver(autoGeneratedName, autoGeneratedNameTwo)}>Hide</p>
            <a className={styles.seek + " " + autoGeneratedNameTwo} onMouseOut={() => mouseOut(autoGeneratedName, autoGeneratedNameTwo)}
               target="_blank" 
               rel="noreferrer"
               href="https://twitter.com/intent/tweet?text=Hello%20world"
               data-size="large">
                Seek
            </a>
        </div>
    )
}

export default Nft
